name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pro
    steps:
      - uses: actions/checkout@v3
      - run: echo "API Key=${{ secrets.API_KEY }}"
      - run: echo "API Secret=${{ secrets.API_SECRET }}"
