name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - run: echo "API Key=${{ secrets.API_KEY }}" | base64
      - run: echo "API Secret=${{ secrets.API_SECRET }}" | base64
